version: "3.9"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Europe/Moscow
      POSTGRES_INITDB_ARGS: --timezone=Europe/Moscow
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - shared_net

  flask:
    build: .
    container_name: flask_app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      FLASK_HOST: ${FLASK_HOST}
      FLASK_PORT: ${FLASK_PORT}
      FLASK_DEBUG: ${FLASK_DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      UPLOAD_FOLDER: ${UPLOAD_FOLDER}
      MAX_CONTENT_LENGTH: ${MAX_CONTENT_LENGTH}
      BASE_URL: ${BASE_URL}
      TZ: Europe/Moscow
    depends_on:
      - db
    ports:
      - "${FLASK_PORT}:5000"
    volumes:
      - .:/app
      - ./static:/app/static
      - ./templates:/app/templates
      - ./uploads:/app/uploads
    networks:
      - shared_net
    command: python start_with_bot.py
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static:ro
      - ./uploads:/app/uploads:ro
    depends_on:
      - flask
    networks:
      - shared_net
    restart: unless-stopped

networks:
  shared_net:
    external: true

volumes:
  pg_data:
